name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes
        id: release_notes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PREV_TAG=$(git describe --tags --abbrev=0 ${GITHUB_REF}^ 2>/dev/null || true)
          if [ -n "$PREV_TAG" ]; then
            git --no-pager log ${PREV_TAG}..${TAG} --pretty=format:"- %s (%h)" > notes.txt || true
          else
            git --no-pager log --pretty=format:"- %s (%h)" > notes.txt || true
          fi
          echo "notes<<EOF_NOTES" >> $GITHUB_OUTPUT
          cat notes.txt >> $GITHUB_OUTPUT
          echo "EOF_NOTES" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref, '-') }}
          draft: true
          body: ${{ steps.release_notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
